### ISSUE TITLE
Documentation for Polygon Incorrect

### ISSUE THREAD

**Issue by cobra5707** [jriecken/sat-js#24]
When I define polygons counter-clockwise the program doesn't work, when I define them clockwise they do. Perhaps the documentation is mistaken?

**Comment by jriecken** [comment]
The screen coordinate system's y-axis is inverted (`(0,0)` is at the top-left of the screen):

So, a polygon specified as `(0,0), (10, 0), (10, 2), (0, 2)` looks like this on the screen:

```
(0,0)------>--------(10,0)
  |                    |
  ^                    V
  |                    |
(0,2)-------<-------(10,2)
```

While this looks like it's clockwise when you draw it like it appears on the screen, it's actually counter-clockwise in the screen coordinate system (because the y-axis is flipped)

What it looks like when viewed as it would be if `(0,0)` was at the bottom-right (as cartesian coordinate systems are usually drawn):
```
(0,2)------<--------(10,2)
  |                    |
  V                    ^
  |                    |
(0,0)----->---------(10,0)
```

See how the arrows are now going counter-clockwise.

Hope this helps!

**Comment by cobra5707** [comment]
Thanks a lot. Is that in the docs?
If not it might be nice to add.

**Comment by jriecken** [comment]
Yeah - good idea - i'll add a note to the docs.

**Comment by jriecken** [comment]
Added a note to the `Polygon` docs in the readme.
