### ISSUE TITLE
Test a circle and this polygon, result is not right

### ISSUE THREAD

**Issue by ks3dev** [jriecken/sat-js#31]
var  polygon  = new SAT.Polygon(new SAT.Vector(0, 0), [
            new SAT.Vector(0, 20),
            new SAT.Vector(8, 50),
            new SAT.Vector(20, 50),
            new SAT.Vector(0, 0)
        ])

Test a circle and this polygon, result is not right..

**Comment by mehmetminanc** [comment]
This is not a proper, i.e. simple polygon.  
![](http://i.cs.hku.hk/~wchu/cgal_manual/doc_html/cgal_manual/Straight_skeleton_2/invalid_polygons.png)

What you have provided will result in a shape similar to that of top-left polygon in the image. If that's what you aimed to achieve, sat.js does not take care of complex polygons.

But it's most likely a mistake in the ordering of points. 

```
var polygon = new SAT.Polygon(new SAT.Vector(0, 0), [
new SAT.Vector(0, 0),
new SAT.Vector(8, 50),
new SAT.Vector(20, 50),
new SAT.Vector(0, 20)
])
```

**Comment by jriecken** [comment]
Actually it is a convex polygon, the points are just specified backwards. This library requires you to specify the points in a counter-clockwise _relative to the coordinate system_ (it _looks_ clockwise if you're drawing them because the y-axis starts at the top of the screen rather than the bottom)

From the readme:

> The points are counter-clockwise with respect to the coordinate system. If you directly draw the points on a screen that has the origin at the top-left corner it will appear visually that the points are being specified clockwise. This is just because of the inversion of the Y-axis when being displayed.

Also take a look at #24 for more explanation.

It should work if you specify your points in the reverse order you have them right now:

```javascript
var polygon = new SAT.Polygon(new SAT.Vector(0, 0), [
  new SAT.Vector(0, 0),
  new SAT.Vector(20, 50),
  new SAT.Vector(8, 50),
  new SAT.Vector(0, 20)
])
```

**Comment by mehmetminanc** [comment]
Ah! I messed up dimensions, somewhere along the rectangle.

I believe this is an indicator that Polygon constructor better take arbitrary points and construct a polygon that is convex hull of those points.
