### ISSUE TITLE
Not triggering collision

### ISSUE THREAD

**Issue by TommyDong1998** [jriecken/sat-js#54]
I got a false from testPolygonPolygon. But the response shows that they are overlapping.
Response {
  a: null,
  b: null,
  overlapN: Vector { x: 0, y: 0 },
  overlapV: Vector { x: 0, y: 0 },
  aInB: true,
  bInA: true,
  overlap: 1.7976931348623157e+308 }

**Comment by jasonbdly** [comment]
I ran the same issue mentioned above. I haven't yet narrowed down what's causing it.
I've simplified the scene to a single ball (simulated by a small square) and a floor (simulated by a wide, thin rectangle), with gravity pulling the ball towards the floor.
Collision detection seems to be working fine when the ball falls on the center section of the floor (about 50% of the floor's width), but anything that lands on the left or right 25% of the floor falls through.

I've attached serialized versions of both Polygon instances as JSON in case that's helpful:
[SmallPolygon.txt](https://github.com/jriecken/sat-js/files/2301247/SmallPolygon.txt)
[FloorPolygon.txt](https://github.com/jriecken/sat-js/files/2301248/FloorPolygon.txt)

Let me know if there's anything else I can provide to help diagnose the issue. In the meantime I'll keep poking around and post back here if I find any useful info.

**Comment by jriecken** [comment]
@TommyDong1998 : Can you share a full example of the polygons that resulted in that return value?

@jasonbdly : Are those values from the position where the collision fails? How fast was the small polygon moving when it fell through? (If the polygon is moving fast enough that it moves more than the width of the polygon it collides with it may "teleport" through it)

Other things I can think of might be very large or very small numbers (double-precision floating point math can get a little sketchy with extremely small (or large) numbers)

**Comment by jasonbdly** [comment]
@jriecken Thanks for the quick response!

The values I provided were pulled from the first frame in which the two polygons would have been colliding, with their velocity already applied. I was concerned about their speed too, given how thin the "floor" is, so I made sure to step through frame-by-frame until they were visibly colliding before grabbing those values.
I'm not clamping the position or velocity values at the moment so it could be a floating point issue.

Here's a short clip to show what's happening, in case it's helpful:
https://streamable.com/bqm0d

As a sidenote, I initially thought it was an issue with my quadtree implementation due to the left/right non-collision areas being almost exactly 25% of the total width of the "floor". I verified that both polygons were being correctly considered for SAT collision detection once they were close enough, so that doesn't seem to be the issue.

**Comment by jasonbdly** [comment]
@jriecken Turns out I was setting up my polygons incorrectly, and it resulted in some overscaled values for "rangeB" in the "isSeparatingAxis" function.
Essentially, I was specifying the points that make up the polygons using their absolute positions instead of their positions relative to the position of the polygon. Guess I should have read the readme more closely!

I'm no longer sure if this is related to @TommyDong1998's issue.

**Comment by jriecken** [comment]
@TommyDong1998 I did a little more investigation, and the values you have in the `Response` there are their initial "cleared" values (see https://github.com/jriecken/sat-js/blob/master/SAT.js#L546). If `testPolygonPolygon` returns false, you shouldn't use any values that are in the response. 

The reason that the `testXxxxYyyy` functions take in an existing `Response` object rather than returning one if there is a collision is so that a single `Response` object can be reused between calls and not have to allocate memory (SAT.js does as close to zero allocations as possible, using shared pools of objects)

The docs could probably be clearer about this so I'll update them

**Comment by jriecken** [comment]
Updated the readme in https://github.com/jriecken/sat-js/commit/4e06e0a81ae38d6630469d94beb1a46d7b5f74bb
