### ISSUE TITLE
testPolygonCircle() Acting Wierd

### ISSUE THREAD

**Issue by ghost** [jriecken/sat-js#66]
Something wrong is going on with the testPolygoCircle() function. Help! I'm trying to rotate a box (a bullet for my game) to hit a circle (a tree stump). It works fine until I use the setAngle() function for my box. Here is a fiddle showing an example of what is going wrong.[https://jsfiddle.net/sharedtakin299/sdghn86b/23/](url) Please tell me what I'm doing wrong.

**Comment by nshen** [comment]
maybe because setAngle should accept angle value instead of radians

```
box.setAngle(50);
```

**Comment by ghost** [comment]
> maybe because setAngle should accept angle value instead of radians
> 
> ```
> box.setAngle(50);
> ```

No, it's not that because the README.md said to use the polygon.setAngle() with radians.

**Comment by jriecken** [comment]
The `rotate` method of the Canvas2D context rotates in a [clockwise direction](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/rotate), while the `setAngle` (and `rotate`) methods of SAT's `Polygon` rotate in a counter-clockwise direction.

If I change your example to do:

```
box.setAngle(-50*Math.PI/180); // rotate in clockwise, rather than counter-clockwise
```

It shows up green

Edit: This isn't the only reason why (see next comment)

**Comment by jriecken** [comment]
Also I think that the way you're drawing the box and circle may not map with what the actual coordinates of the SAT objects are.

```
var b = {x:100,y:100,w:100,h:100};
var response = new SAT.Response();

// Make boxes and set angle to 45 degrees
var box = new B(new V(b.x,b.y),b.w,b.h).toPolygon();
box.setAngle(50*Math.PI/180);
```

This will rotate the box around its corner, not the middle, while when you're drawing the box, you're translating the context to be at the box's middle before rotating it.

```
ctx.save();
ctx.translate(b.x+b.w/2,b.y+b.h/2);
ctx.rotate(50*Math.PI/180);
ctx.translate(-b.x-b.w/2,-b.y-b.h/2);
ctx.fillRect(b.x,b.y,b.w,b.h);
ctx.restore();
```

---

If you also do

```
box.setOffset(-50, -50);
```

I think it will do the same as what your drawing code is

**Comment by ghost** [comment]
> Also I think that the way you're drawing the box and circle may not map with what the actual coordinates of the SAT objects are.
> 
> ```
> var b = {x:100,y:100,w:100,h:100};
> var response = new SAT.Response();
> 
> // Make boxes and set angle to 45 degrees
> var box = new B(new V(b.x,b.y),b.w,b.h).toPolygon();
> box.setAngle(50*Math.PI/180);
> ```
> 
> This will rotate the box around its corner, not the middle, while when you're drawing the box, you're translating the context to be at the box's middle before rotating it.
> 
> ```
> ctx.save();
> ctx.translate(b.x+b.w/2,b.y+b.h/2);
> ctx.rotate(50*Math.PI/180);
> ctx.translate(-b.x-b.w/2,-b.y-b.h/2);
> ctx.fillRect(b.x,b.y,b.w,b.h);
> ctx.restore();
> ```
> 
> If you also do
> 
> ```
> box.setOffset(-50, -50);
> ```
> 
> I think it will do the same as what your drawing code is

I hate to bother you, but it still is not working. I implemented the two things you told me, but it is doing the exact opposite now. Here is my updated JSFiddle   [https://jsfiddle.net/sharedtakin299/sdghn86b/27/](url)  I used the box.setOffset() and switched the rotation to clockwise, but it still is not working. I'm confused. Am I still doing something wrong?

**Comment by jriecken** [comment]
🤦 Sorry, it's clearly been a while since I've looked at this code - the `setOffset` method takes in a `Vector`, so it would be `box.setOffset(new SAT.Vector(-50,-50))`. You'll also have to adjust the `pos` of the `box` (but not your current drawing code) to account for the offset (e.g `box.pos.x += 50; box.pos.y += 50;`)

Here are two examples with it working:

Not Colliding: https://jsfiddle.net/get2jkx1/

Colliding (added 10 to the `x` position so they intersect): https://jsfiddle.net/get2jkx1/1/

**Comment by ghost** [comment]
> 🤦 Sorry, it's clearly been a while since I've looked at this code - the `setOffset` method takes in a `Vector`, so it would be `box.setOffset(new SAT.Vector(-50,-50))`. You'll also have to adjust the `pos` of the `box` (but not your current drawing code) to account for the offset (e.g `box.pos.x += 50; box.pos.y += 50;`)
> 
> Here are two examples with it working:
> 
> Not Colliding: https://jsfiddle.net/get2jkx1/
> 
> Colliding (added 10 to the `x` position so they intersect): https://jsfiddle.net/get2jkx1/1/

Thanks so much! Man was I confused!

**Comment by ramontavarez** [comment]
Hey @jriecken 
I have the same issue but for me that solution not works until now, maybe im doing something wrong, can you help me?

In my case, the polygon is a projectile that moves until it collides with a circle (player).
that's my projectile/bullet code on server side:
![image](https://github.com/jriecken/sat-js/assets/10215019/5d56c912-1e8a-45a7-a489-e2ac14c4e8a9)

**EDIT 1**: _x and y in this code come from player position 
and i already tested a circleCircle collision with 2 players and it works as expected_

The movement is working well, also the angle too... but the collision not.
In your example, you update the pos with `x += width / 2, y += height / 2` right?
when i try this in my `updateShape` function, it messed up, propably because of the movement in a specific angle.
In this case, how can i do this work? 

Im using PIXI.js on clientside and i reproduce all the positions and angle from server side in my projectile in client side
as i said before, it works well, but the collision not.

I made a video to show you:
https://clipchamp.com/watch/AAw4d7YYzws

In clientside the projectile is a Sprite with anchor set to 0.5

**EDIT 2:**
- When i dont move the shape it works well, even when its rotated
- When i change the velocity to 1 or less it works more fine

**EDIT 3:**
- ok, it seens like a sync issue through server and client xD
- i tried to not delete the projectile on server side instead of this i just stopped it to see on client side where the projectile stop and i saw its stop the right location where it collides, so the problem is my code =D
