### ISSUE TITLE
[BUG] pointInPolygon gave wrong result

### ISSUE THREAD

**Issue by bxclib2** [jriecken/sat-js#69]
// npm install sat
// sat js
```
var points = [
new SAT.Vector(958.465800982533, 115.41687755787399),
new SAT.Vector(1565.7857895122002, 690.9971131309669),
new SAT.Vector(536.2902104877998, 560.8728868690332),
new SAT.Vector(1143.610199017467, 1136.4531224421262)
];

var polygon = new SAT.Polygon(new SAT.Vector(), points);

var point = new SAT.Vector(1529.4582839066827, 1132.463424278371);

var isInside = SAT.pointInPolygon(point, polygon);

console.log(isInside); // should be false. Give True
```

I checked the implementation. It seems the implementation uses the testPolygonPolygon to test the point in Polygon?

In fact when the Polygon has only one point, the testPolygonPolygon function is not implemented correctly. It has bugs.

Because the normal direction is undefined, the separate axis theorem cannot directly be used here. It is a special case need to be checked.

**Comment by jriecken** [comment]
This library only works with **convex** polygons. The shape you have described with the points is not a convex polygon - it's more of a bowtie shape where two of the edges cross each other..

(I shifted the decimal 2 places left from your coordinates to plot this and stripped some of the fractional part)

`(9.58, 1.15), (15.65, 6.90), (5.36, 5.60), (11.43, 11.36)`

![image](https://github.com/jriecken/sat-js/assets/408825/cc47c2e8-3d1c-44ff-804e-8d4e4ffb468f)



From the README:

> SAT.Polygon
>
> This is a **convex polygon**, whose points are specified in a **counter-clockwise** fashion.
>
> Note: The points are **counter-clockwise with respect to the coordinate system**. If you directly draw the points on a screen that has the origin at the top-left corner it will appear visually that the points are being specified clockwise. This is just because of the inversion of the Y-axis when being displayed.

What you're seeing is not a bug, it's undefined behavior because the polygon is not following the rules.

If you want to use you shape you will need to represent it as two separate polygons and perform the hit test against both.

---

Also, while `pointInPolygon`  _is_ implemented with `testPolygonPolygon` it uses a tiny square of size `0.000001` by `0.000001` at the position specified so the SAT still works. This does mean that if you have something smaller than that, it may not work, but if we were to assume that a value of `1` is 1 meter, it would be something smaller than 1 micrometer.

**Comment by bxclib2** [comment]
okay I see thanks for your quick reply
